#!/bin/sh

#If ibam is installed, use it for more accurate estimates:
ibam=`which ibam`
pidfile=~/.battery.pid

WMIINORMCOLORS="#888888 #222222 #333333"
fullcolours="#88bb88 #223322 #333333"
warncolours="#ffcc88 #222222 #333333"
critcolours="#ffcc88 #443322 #333333"
colours="$WMIINORMCOLORS"

state='cat /proc/acpi/battery/BAT0/state'
info='cat /proc/acpi/battery/BAT0/info'

battery() {
  if [ `$state|awk '/^present:/ {print $2}'` == no ]; then
    echo -n "$colours no battery"
  fi

  presentrate=`$state|awk '/^present rate:/ {print $3}'`

  if [ $ibam ]; then
  #if false; then  #DEBUG
    percent=`$ibam --percentbattery|awk '/^Battery percentage/ {print $3}'`
    charge=`$ibam|awk '/^Charge time left/ {print $4}'`
    battery=`$ibam|awk '/^Battery time left/ {print $4}'`
  else
    chargingstate=`$state|awk '/^charging state:/ {print $3}'`
    remainingcapacity=`$state|awk '/^remaining capacity:/ {print $3}'`
    designcapacity=`$info|awk '/^design capacity:/ {print $3}'`
    lastfullcapacity=`$info|awk '/^last full capacity:/ {print $4}'`

    #percent=$[ $remainingcapacity * 100 / $designcapacity ]
    percent=$[ $remainingcapacity * 100 / $lastfullcapacity ]

    if [ $chargingstate == "discharging" ]; then
      seconds=$[ $remainingcapacity*60*60 / $presentrate ]
      hours=$[ $seconds/60/60 ]
      minutes=$[ $seconds/60%60 ]
      seconds=$[ $seconds%60 ]
      battery=`printf %i:%.2i:%.2i $hours $minutes $seconds`
    elif [ $chargingstate == "charging" ]; then
      seconds=$[ ($lastfullcapacity-$remainingcapacity)*60*60 / $presentrate ]
      hours=$[ $seconds/60/60 ]
      minutes=$[ $seconds/60%60 ]
      seconds=$[ $seconds%60 ]
      charge=`printf %i:%.2i:%.2i $hours $minutes $seconds`
    fi
  fi
  
  if [ $charge ]; then
    false
  elif [ $battery ]; then
    if [ `echo $battery|awk -F: '{print $1}'` -eq 0 ]; then
      if [ `echo $battery|awk -F: '{print $2}'` -le 5 ]; then
        colours="$critcolours"
      elif [ `echo $battery|awk -F: '{print $2}'` -le 15 ]; then
        colours="$warncolours"
      fi
    fi
  elif [ $percent -eq 100 ]; then
    colours="$fullcolours"
  fi

  if [ $charge$battery ]; then
    echo -n "$colours $percent% (${charge}${battery} @ ${presentrate}mA) $anim"
  else
    echo -n "$colours $percent% $anim"
  fi
}

#set +xv
echo "$WMII_NORMCOLORS" | wmiir create /rbar/aaa
if [ -z $ibam ]; then
  echo "$warncolours ibam is not installed - battery estimate will be less reliable" | wmiir create /rbar/batteryz
  sleep 2
fi
if wmiir remove /rbar/battery 2>/dev/null; then
  kill `cat $pidfile` 2>/dev/null
fi
echo $$ > $pidfile
wmiir remove /rbar/batteryz 2>/dev/null
echo "$WMII_NORMCOLORS" | wmiir create /rbar/battery
while battery | wmiir write /rbar/battery; do
	sleep 30
done
rm $pidfile
