#!/bin/sh

oldview=`wmiir read /ctl | awk '/^view / {print $2}'`
wmiir xwrite /ctl view "lock"
sleep 0.1
xset dpms force suspend
(
  while true; do
    result=`xset q | grep 'Monitor is On'`
    if [ "$result" ]; then
			sleep 5
	    xset dpms force suspend
    fi
    sleep 10
  done
) &
eval /usr/bin/xtrlock
kill %%
wmiir xwrite /ctl view "$oldview"
#cat /sys/class/backlight/eeepc/brightness
